Update pipelines

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -18,9 +18,9 @@ jobs:
       uses: actions/checkout@v4
 
     - name: Setup .NET
-      uses: actions/setup-dotnet@v3
+      uses: actions/setup-dotnet@v4
       with:
-        dotnet-version: 7.0.x
+        dotnet-version: 8.0.x
 
     - name: Restore dependencies
       run: dotnet restore
@@ -28,9 +28,6 @@ jobs:
     - name: Build solution
       run: dotnet build -c ${{ env.CONFIGURATION }} --no-restore
 
-    - name: Run Mafin.Web.UI.Selenium.Example tests
-      run: dotnet test Mafin.Web.UI.Selenium.Example/*.csproj -c ${{ env.CONFIGURATION }} --no-build
-
     - name: Run Mafin.Web.UI.Selenium.YapomlExample tests
       run: dotnet test Mafin.Web.UI.Selenium.YapomlExample/*.csproj -c ${{ env.CONFIGURATION }} --no-build
-      if: success() || failure()
+      #if: success() || failure()
